# Name of the model to 3D plot
model_name: /HalfBottleneck3CIFAR10_100_0_0_0_0_0percent_9.9epochs:v0

# If the negative flip are going to be calculated and shown in the 3D plot
nfr: False

# If a convex hull is added to the 3D plot, only possible if there is no negative flips calculations
add_convex_hull : True