# percentage of CIFAR10 to use
percentage : 100

# which classes have a lower percentage of images
low_class_list: null
low_percentage: [100]

epochs : 9.9

# If NFR is going to be calculated after each epoch
nfr: True
old_model : /HalfBottleneck3CIFAR10_100_0_0_0_0_0percent_9.9epochs:v0

loss: 'default'