# percentage of CIFAR10 to use
percentage : 50

# which classes have a lower percentage of images
low_class_list: null
low_percentage: [100]

epochs : 4

# If NFR is going to be calculated after each epoch
nfr: False