model_name: /CIFAR10_100_1_1percent_9.9epochs:v0

# Number of swaps to attempt before giving up
patience: 100

# Largest possible logit activatio
logit_upper_bound: 100

# Smallest possible logit activation
logit_lower_bound : -100
