# Name of the trained model
model_name : 'Test'

# Number of models that are going to be trained
num_models : 10
# percentage of CIFAR10 to use
percentage : 100

# Number of classes that the model will classify
num_classes: 10
# List of classes that have a lower percentage of images, if null all the images are going to be used
low_class_list: null
# List containing the images' percentage used for each class in low_class_list
low_percentage: None

epochs : 15

# Seed for reproducibility
seed : 111

# Features' dimension, if the dSimplex is used feat_dim = num_classes -1
feat_dim : 256     # standard is 256
# If the classifier is a dSimplex
dSimplex : False

# If NFR is going to be calculated after each epoch
nfr: True
old_model : /New_stuff_first_5_classes_CIFAR10_100_0_0_0_0_0percent_9epochs:v0
old_num_classes : 5

loss: 'New stuff'

FD: False        # add FD to loss
fd_alpha : 1
fd_beta : 5
focus_type : 'old_correct'
distillation_type : 'kl'
kl_temperature : 100
lambda : 50

CF : False      # add Contrastive Feature Loss
tau_f:  10
lambda_f: 50
only_old: False   # if the loss is applied only to features of images that belong to the old classes

CP : False      # add Contrastive Prototype Loss
tau_p:  10
lambda_p: 75

CPL: False       # add Cosine Prototype Loss
lambda_cpl: 1

CDP: False       # add Cosine Difference Prototype Loss
lambda_cdp: 50

PACE: True
lambda_pa : 0
k : 3
pretrained: True    # If the knn matrix is going to be calculated with a pretrained model or the average of regularly trained ones
guide_model: /Big_features_Regular_Training_CIFAR10_100_onpercent_15epochs:v0 # name of the guide model to calculate knn_matrix
num_guide_models: 100
