# Names of the gallery and query models
gallery_model_name: /old_model_name:v0
query_model_name: /model_name:v0

# Number of query models to evaluate
num_models : 5

# String that defines the type of output to compare, can be: 'features' 'logits' or 'softmax'
output_type : 'features'

# Testing dataloader's batch size
batch_size : 256

# ResNet parameters
backbone: 'resnet18'
feat_dim : 512
num_classes_gallery_model : 50
num_classes_query_model: 100

old_backbone: 'resnet18'  #backbone of the old gallery model
old_feat_dim: 512

# Dataset parameters
subset_list : null  #es: list [0,50,1] corresponds to list(range(0,50,1)), None = all classes
