# Names of the gallery and query models
gallery_model_name: /Re-Training_full_CIFAR100:v0
query_model_name: /Resnet34_Training_FD_KL_lambda_1_full_CIFAR100:v0

# Number of query models to evaluate
num_models : 5

 # String that defines the type of output to compare, can be: 'features' 'logits' or 'softmax'
output_type : 'softmax'

# Testing dataloader's batch size
batch_size : 256

# ResNet parameters
backbone: 'resnet34'
feat_dim : 512
num_classes_gallery_model : 100
num_classes_query_model: 100

old_backbone: 'resnet18'  #backbone of the old model
old_feat_dim: 512

# Dataset parameters
subset_list : null  #es: list [0,50,1] corresponds to list(range(0,50,1)), None = all classes
