# Model's name. Models have to be named as: /model_name:v_num 
model_name: /Re-Training_full_CIFAR100:v0
num_models : 5

# Testing dataloader's batch size
batch_size : 256

# ResNet parameters
backbone: 'resnet18'
feat_dim : 512

# Dataset parameters
num_classes : 100
subset_list : null    #es: list [0,50,1] corresponds to list(range(0,50,1)), None = all classes

# If NFR is going to be calculated after testing
nfr: True
old_model_name : /Re-Training_CIFAR100_first_50_classes_numclasses_50:v0
old_subset_list: [0,50,1]

# If the classifier is a dSimplex
dSimplex : False