# Model's name. Models have to be named as: /model_name:v_num 
model_name: /Training_CIFAR100_first_50_classes:v0

# Testing dataloader's batch size
batch_size : 128

# ResNet parameters
backbone: 'resnet18'
feat_dim : 512

# Dataset parameters
num_classes : 100
subset_list : [0,50,1]    #es: list [0,50,1] corresponds to list(range(0,50,1)), None = all classes

# If NFR is going to be calculated after testing
nfr: False
old_model_name : null
old_subset_list: null

# If the classifier is a dSimplex
dSimplex : False