wandb_name: "Smaller feat Resnet18 CF_0.15_CP_1.5"  

# Training hyperparameters
train_epochs : 200
batch_size : 256
lr :  0.1
milestones : [60, 120, 160]
momentum : 0.9
weight_decay : 5.0e-4

# ResNet parameters
backbone: 'resnet18'
feat_dim : 32
pretrained : False

# Dataset parameters
num_classes : 100
subset_list : null    #es: list [0,50,1] corresponds to list(range(0,50,1)), null = all classes

# Number of models that are going to be trained
num_models : 5

# Seed for reproducibility
seed : 111

# If the classifier is a dSimplex
dSimplex : False

# If NFR is going to be calculated after each epoch
nfr: True
nfr_eval: 20    # after how many epochs to evaluate the NRF
old_model_name : /Smaller_feat_Resnet18_Training_half_CIFAR100:v0
old_subset_list: [0,50,1]
old_backbone: 'resnet18'  #backbone of the old model
old_feat_dim: 32

loss: 'New stuff'

FD: False        # add FD to loss
fd_alpha : 1
fd_beta : 5
focus_type : 'old_correct'
distillation_type : 'kl'
kl_temperature : 100
lambda : 1

CF : True      # add Contrastive Feature Loss
tau_f:  10
lambda_f: 0.15
only_old: False   # if the loss is applied only to features of images that belong to the old classes

CP : True      # add Contrastive Prototype Loss
tau_p:  10
lambda_p: 1.5

CPL: False       # add Cosine Prototype Loss
lambda_cpl: 50    

PACE: False
