wandb_name: "Training FD KL lambda 1 full CIFAR100"

# Training hyperparameters
train_epochs : 200
batch_size : 128
lr :  0.1
milestones : [60, 120, 160]
momentum : 0.9
weight_decay : 5.0e-4

# ResNet parameters
backbone: 'resnet18'
feat_dim : 512
pretrained : False

# Dataset parameters
num_classes : 100
subset_list : null    #es: list [0,50,1] corresponds to list(range(0,50,1)), null = all classes

# Number of models that are going to be trained
num_models : 4

# Seed for reproducibility
seed : 112

# If NFR is going to be calculated after each epoch
nfr: True
old_model_name : /Training_CIFAR100_first_50_classes:v0
old_subset_list: [0,50,1]

loss: 'Focal Distillation'
fd_alpha : 1
fd_beta : 5
focus_type : 'old_correct'
distillation_type : 'kl'
kl_temperature : 100
lambda : 1

# If the classifier is a dSimplex
dSimplex : False